name: Async Function Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create package.json
        run: |
          echo '{
            "name": "asynchronous-functions",
            "version": "1.0.0",
            "description": "Testing asynchronous functions",
            "main": "code.js",
            "scripts": {
              "test": "node code.test.js"
            },
            "dependencies": {},
            "devDependencies": {
              "jsverify": "^0.8.4"
            }
          }' > package.json

      - name: Install dependencies
        run: npm install

      - name: Run async function tests
        run: npm test
